In [5]:
import tensorflow as tf
v=tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
v1=tf.constant([1.0,2.0,3.0])
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    print(sess.run(tf.clip_by_value(v,2.5,4.5)))
    print(sess.run(tf.log(v1)))

[[ 2.5  2.5  3. ]
 [ 4.   4.5  4.5]]
[ 0.          0.69314718  1.09861231]


In [8]:
v1=tf.constant([[1.0,2.0],[3.0,4.0]])
v2=tf.constant([[5.0,6.0],[7.0,8.0]])
v=tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
with tf.Session() as sess:
    print(sess.run((v1*v2)))
    print(sess.run(tf.matmul(v1,v2)))
    print(sess.run(tf.reduce_mean(v)))

[[  5.  12.]
 [ 21.  32.]]
[[ 19.  22.]
 [ 43.  50.]]
3.5
