In [5]:
import numpy as np
a=np.random.randn(4,3)
b=np.random.randn(3,2)

In [4]:
a

array([[ 0.20396265, -1.73758918,  2.09619576],
       [-0.26836162, -0.752612  , -1.95135909],
       [ 0.3896046 ,  0.79265957,  0.0724769 ],
       [-0.59684995, -1.83622187, -1.85010913]])

In [6]:
b

array([[ 0.09845873, -0.3395253 ],
       [-1.96414407, -0.21672092],
       [-0.67120558, -0.24426103]])

In [7]:
c=np.dot(a,b)

In [8]:
c

array([[ 0.33069474, -0.52425986],
       [ 0.13418844, -0.67290969],
       [ 0.31674533, -0.3295713 ],
       [ 1.92612147, -0.22702489]])

In [9]:
a=np.random.randn(3,3)
b=np.random.randn(3,1)
c=a*b

In [10]:
c

array([[ 0.07910931,  0.17987978, -0.22956393],
       [-0.4977361 , -0.13919287, -0.61068115],
       [ 0.08500744, -0.11411453, -0.03648708]])

In [11]:
a.shape

(3, 3)

In [12]:
b.shape

(3, 1)